export const meta = {
    title: "Create Next App",
    description: "Generated by create next app",
    lang: "zh-tw",
    icon: "@/assests/logo_s.png",
}

  
export function Meta() {
    return (
        <head>
            <title>{meta.title}</title>
            <meta name="description" content={meta.description} />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href={meta.icon} />
        </head>
    )
}